package com.example.hibernatetest2.tables.manytoone.service;

import java.util.ArrayList;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;

import com.example.hibernatetest2.tables.manytoone.dto.Table2Dto;
import com.example.hibernatetest2.tables.manytoone.dto.mapper.Table2Mapper;
import com.example.hibernatetest2.tables.manytoone.entities.QTable2;
import com.example.hibernatetest2.tables.manytoone.entities.Table2;
import com.example.hibernatetest2.tables.manytoone.repositories.Table2Repository;
import com.example.hibernatetest2.tables.manytoone.repositories.Table2RepositoryCustomQueryDslImpl;
import com.querydsl.core.types.ExpressionUtils;
import com.querydsl.core.types.Predicate;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Service
@RequiredArgsConstructor
@Slf4j
public class Table2Service {

    private final Table2Repository table2Repository;

    private final Table2RepositoryCustomQueryDslImpl table2RepositoryCustom;

    private final Table2Mapper table2Mapper;


    public Page<Table2Dto> search(
                                  Integer pageNumber,
                                  Integer numberOfRowsInOnePage,
                                  String sortedBy,
                                  String searchPhrase) {
        var pageRequest = PageRequest.of(pageNumber,
                                         numberOfRowsInOnePage,
                                         Sort.by(Sort.Direction.DESC,
                                                 sortedBy));
        var listOfBooleanExpressions = new ArrayList<Predicate>(); //! You need QueryDsl dependency for this to work
        String[] arr = searchPhrase.split(" "); //! http://website.com/?searchPhrase=me+th parses internally as searchPhrase = "me th"
        for (String currentWord : arr) {
            listOfBooleanExpressions.add(QTable2.table2.name.containsIgnoreCase(currentWord)); //[ ] QTable1 is a class generated by QueryDsl. You need to change it to class that represents your table, like QMyTable
        }
        var predicate = ExpressionUtils.anyOf(listOfBooleanExpressions); //? Connects QueryDslPredicate1s with logivcanl OR
        return table2Repository.findAll(predicate, pageRequest).map(table2Mapper::table2ToDto);
    }

    public Table2Dto findById(Long id) {
        var optionalRowFromTable2 = table2Repository.findById(id);
        return table2Mapper.table2ToDto(optionalRowFromTable2.get());
    }

    public Table2Dto createNewRow(Table2 creatingForm) {
        return table2Mapper.table2ToDto(table2Repository.saveAndFlush(creatingForm));
    }

    public Table2Dto changeRow(String newName, Long id) {
        var rowToChange = table2Repository.findById(id).get();
        rowToChange.setName(newName);
        return table2Mapper.table2ToDto(table2Repository.saveAndFlush(rowToChange));
    }

    public int deleteRow(String name) {
        return table2Repository.deleteByName(name);
    }

}
