package com.example.hibernatetest2.tables.embedded.service;

import java.util.ArrayList;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;

import com.example.hibernatetest2.tables.embedded.dto.Table5Dto;
import com.example.hibernatetest2.tables.embedded.dto.mapper.Table5Mapper;
import com.example.hibernatetest2.tables.embedded.entities.QTable5;
import com.example.hibernatetest2.tables.embedded.entities.Table5;
import com.example.hibernatetest2.tables.embedded.repositories.Table5Repository;
import com.example.hibernatetest2.tables.embedded.repositories.Table5RepositoryCustomQueryDslImpl;
import com.querydsl.core.types.ExpressionUtils;
import com.querydsl.core.types.Predicate;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Service
@RequiredArgsConstructor
@Slf4j
public class Table5Service {

    private final Table5Repository table2Repository;

    private final Table5RepositoryCustomQueryDslImpl table2RepositoryCustom;

    private final Table5Mapper table2Mapper;


    public Page<Table5Dto> search(
                                  Integer pageNumber,
                                  Integer numberOfRowsInOnePage,
                                  String sortedBy,
                                  String searchPhrase) {
        var pageRequest = PageRequest.of(pageNumber,
                                         numberOfRowsInOnePage,
                                         Sort.by(Sort.Direction.DESC,
                                                 sortedBy));
        var listOfBooleanExpressions = new ArrayList<Predicate>(); //! You need QueryDsl dependency for this to work
        String[] arr = searchPhrase.split(" "); //! http://website.com/?searchPhrase=me+th parses internally as searchPhrase = "me th"
        for (String currentWord : arr) {
            listOfBooleanExpressions.add(QTable5.table5.name.containsIgnoreCase(currentWord)); //[ ] QTable1 is a class generated by QueryDsl. You need to change it to class that represents your table, like QMyTable
        }
        var predicate = ExpressionUtils.anyOf(listOfBooleanExpressions); //? Connects QueryDslPredicate1s with logivcanl OR
        return table2Repository.findAll(predicate, pageRequest).map(table2Mapper::table2ToDto);
    }

    public Table5Dto findById(Long id) {
        var optionalRowFromTable2 = table2Repository.findById(id);
        return table2Mapper.table2ToDto(optionalRowFromTable2.get());
    }

    public Table5Dto createNewRow(Table5 creatingForm) {
        return table2Mapper.table2ToDto(table2Repository.saveAndFlush(creatingForm));
    }

    public Table5Dto changeRow(String newName, Long id) {
        var rowToChange = table2Repository.findById(id).get();
        rowToChange.setName(newName);
        return table2Mapper.table2ToDto(table2Repository.saveAndFlush(rowToChange));
    }

    public int deleteRow(String name) {
        return table2Repository.deleteByName(name);
    }
}
