DROP TABLE IF EXISTS table2;

DROP TABLE IF EXISTS table1;

CREATE TABLE IF NOT EXISTS table1 ( /*? One to Many */
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name       VARCHAR (255) NOT NULL UNIQUE,
    enumeration VARCHAR (255),
    PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS table2 ( /*? Many to One */
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name       VARCHAR (255) NOT NULL UNIQUE,
    table1_id  BIGINT UNSIGNED,
    enumeration VARCHAR (255),
    FOREIGN KEY (table1_id) REFERENCES table1 (id),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Users
(
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name  VARCHAR(50) NOT NULL,
    email      VARCHAR(100) NOT NULL,
    password   VARCHAR(255) DEFAULT NULL,
    address    VARCHAR(255) DEFAULT NULL,
    phone      VARCHAR(30) DEFAULT NULL,
    title      VARCHAR(50) DEFAULT NULL,
    bio        VARCHAR(255) DEFAULT NULL,
    enabled    BOOLEAN DEFAULT FALSE,
    non_locked BOOLEAN DEFAULT TRUE,
    using_mfa  BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    image_url  VARCHAR(255) DEFAULT 'https://cdn-icons-png.flaticon.com/512/149/149071.png',
    CONSTRAINT UQ_Users_Email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS Roles
(
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(50) NOT NULL,
    permission VARCHAR(255) NOT NULL,
    CONSTRAINT UQ_Roles_Name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS UserRoles
(
    id      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    role_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (role_id) REFERENCES Roles (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT UQ_UserRoles_User_Id UNIQUE (user_id)
);
